version: '3.4'
services:
  frontend:
    platform: linux/x86_64
    image: ghcr.io/dyzhuu/msafrontend:main
    container_name: frontend

  backend:
    platform: linux/x86_64
    image: ghcr.io/dyzhuu/msabackend:main
    container_name: backend
