version: '3.4'
services:
  backend:
    build: ./backend
    image: ghcr.io/dyzhuu/msabackend:main
    # image: dyzhuu/msabackend:latest
    container_name: backend
    ports:
    - 8080:8080
    expose: 
    - "8080"
    restart: always

  frontend:
    build: ./frontend
    image: ghcr.io/dyzhuu/msafrontend:main
    # image: dyzhuu/msafrontend:latest
    container_name: frontend
    links:
      - "backend"
    ports:
    - 80:80
    depends_on:
    - backend