version: '3.4'
services:
  frontend:
    build: ./frontend
    platform: linux/x86_64
    image: ghcr.io/dyzhuu/msafrontend:main
    container_name: frontend
    ports:
    - 80:80
    - 443:80

  backend:
    build: ./backend
    platform: linux/x86_64
    image: ghcr.io/dyzhuu/msabackend:main
    container_name: backend
    ports:
    - 8080:8080