version: '3.4'
services:
  frontend:
    build: ./frontend
    platform: linux/x86_64
    image: ghcr.io/dyzhuu/msa:frontend
    container_name: frontend
    ports:
    - 80:80
    - 443:80

  backend:
    build: ./backend
    platform: linux/x86_64
    image: ghcr.io/dyzhuu/msa:backend
    container_name: backend
    ports:
    - 80:5000
