version: '3.4'
services:
  backend:
    image: 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # other backend service configurations

  frontend:
    image: 'frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # other frontend service configurations
