version: '3.4'
services:
  backend:
    build: ./backend
    image: ghcr.io/dyzhuu/msabackend:main
    container_name: backend
    ports:
    - 8080:8080 
    restart: always

  frontend:
    build: ./frontend
    image: ghcr.io/dyzhuu/msafrontend:main
    container_name: frontend
    ports:
    - 80:80