name: CICD_Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./backend
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./backend
