# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - davidzhumsa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_27361d7745e745a4ae33ab8415d4232a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cda470bd5b2848d99e8c3733d9ca078c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_27361d7745e745a4ae33ab8415d4232a }}/dyzhuu/msafrontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'davidzhumsa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_20ceb328a502423d97914e68c2354b74 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_27361d7745e745a4ae33ab8415d4232a }}/dyzhuu/msafrontend:${{ github.sha }}'